from practiceapp.Serializers.PlaceSerializer import PlaceSerializer
# from practiceapp.Serializers.MovieSerializer import MovieSerializer
# from practiceapp.Serializers.ProductSerializer import ProductSerializer