# Generated by Django 3.0.2 on 2020-02-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=120)),
                ('description', models.CharField(db_column='Description', max_length=100)),
                ('body', models.CharField(db_column='Body', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('end_date', models.DateField()),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('ProdcutId', models.AutoField(db_column='Product Id', primary_key=True, serialize=False)),
                ('ProdcutName', models.CharField(db_column='Product Name', max_length=100)),
                ('ProdcutPrice', models.IntegerField(db_column='Product Price')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('practiceapp.place',),
        ),
    ]
